### ISSUE TITLE
TODO For 2.0.0 Release

### ISSUE THREAD

**Issue by Skyladd** [Skyladd/ChestShop#11]
**TODO**
- [x] Either disable double chest shops or support them
- Double ChestShops are now supported [Some modifications can be made still]
- [ ] Add sell shops
- Will add sell shops sooner or later
- [ ] Clean up code
